services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gestion_pet
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=64M
      --innodb-log-file-size=16M
      --max-connections=20
      --performance-schema=OFF
      --table-open-cache=64
      --thread-cache-size=4
      --tmp-table-size=16M
      --max-heap-table-size=16M
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  mysql_data: